---

- name: manage esadmin directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_base_dir }}"

- name: check if certs file exists
  stat: 
    path: "{{ server_cert_file }}"
  register: cert_created

- name: Test whether that certificate is valid for next 7 days
  openssl_certificate_info:
    path: "{{ server_cert_file }}"
    valid_at:
      point_1: "+7d"
  register: cert_info
  when: cert_created.stat.exists == true

- name: generate docker tls certs
  include: docker/generate_certs.yml
  when: cert_created.stat.exists == false or 
    cert_info.valid_at.point_1 == false

- name: upload ssm keys
  include: docker/manage_ssm.yml

