---
# tasks/ssm/create_ssm.yml

- name: get ca cert file # noqa 301
  command: "cat {{ server_cert_file }}"
  no_log: true
  register: ca_cert

- name: get server key file # noqa 301
  command: "cat {{ server_key_file }}"
  no_log: true
  register: server_key

- name: get server cert file # noqa 301
  command: "cat {{ server_cert_file }}"
  no_log: true
  register: server_cert

- name: set docker tls cert data facts
  set_fact:
    docker_ca: "{{ ca_cert.stdout }}"
    docker_cert: "{{ server_cert.stdout }}"
    docker_key: "{{ server_key.stdout }}"

- name: upload ca cert in ssm store
  aws_ssm_parameter_store:
    name: "{{ ssm_ca_param_name }}"
    description: "{{ common_name }} ca cert"
    string_type: "String"
    value: "{{ docker_ca }}"
    overwrite_value: "{{ ssm_overwrite }}"
    region: "{{ aws_region }}"

- name: upload server cert in ssm store
  aws_ssm_parameter_store:
    name: "{{ ssm_server_cert_param_name }}"
    description: "{{ common_name }} server cert"
    string_type: "String"
    value: "{{ docker_cert }}"
    overwrite_value: "{{ ssm_overwrite }}"
    region: "{{ aws_region }}"

- name: upload server key in ssm store
  aws_ssm_parameter_store:
    name: "{{ ssm_server_key_param_name }}"
    description: "{{ common_name }} server key"
    string_type: "SecureString"
    value: "{{ docker_key }}"
    overwrite_value: "{{ ssm_overwrite }}"
    region: "{{ aws_region }}"
