---
# tasks/docker/main.yml

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

- name: configure docker
  include_tasks: docker-config.yml
  when: ansible_service_mgr == 'systemd'

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- name: setup docker-compose
  include_tasks: docker/docker-compose.yml
  when: docker_install_compose | bool

- name: manage docker users
  include_tasks: docker/docker-users.yml
  when: docker_users | length > 0
